good_citizen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quizz.urls")),
]

handler404 = "quizz.views.page_not_found_view"
handler500 = "quizz.views.page_server_not_found"

quizz/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("",
         TemplateView.as_view(template_name="core/home.html"),
         name="home"),
    path("accueil",
         TemplateView.as_view(template_name="core/home.html"),
         name="home"),
    url("mentions-legales",
        TemplateView.as_view(template_name="core/legal.html")),
    path("creer-compte", views.account_create, name="account_create"),
    path("mon-compte", views.account, name="account"),
    path(
        "connexion",
        auth_views.LoginView.as_view(
            template_name="account/connect.html",
            redirect_authenticated_user=True
        ),
        name="login",
    ),
    path(
        "changer-mdp",
        auth_views.PasswordChangeView.as_view(
            template_name="account/change_pwd.html", success_url="connexion"
        ),
        name="pwd_change",
    ),
    path(
        "reset-mdp",
        auth_views.PasswordResetView.as_view(
            template_name="account/reset_pwd.html",
            email_template_name="account/reset_email.html",
        ),
        name="reset_pwd",
    ),
    path(
        "reset-mdp-envoye",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/reset_pwd_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/reset_pwd_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-mdp-termine",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("deconnexion", auth_views.LogoutView.as_view(), name="deconnexion"),
    url(r"^quizz/$", views.quizz, name="quizz"),
    path("quizz/<int:id_quizz>", views.unique_quizz, name="quizz_page"),
    path("resultats", views.results, name="results"),
]

quizz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=150, unique=True)
    quizz_done = models.ManyToManyField("Quizz", through="Result")

    class Meta:
        verbose_name = "User"

    def __str__(self):

        return self.username


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    class Meta:
        verbose_name = "Catégorie"

    def __str__(self):

        return self.name


class Quizz(models.Model):
    name = models.CharField(max_length=255, unique=True)
    create_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL,
                                 null=True)

    class Meta:
        verbose_name = "Quizz"

    def __str__(self):

        return self.name


class Question(models.Model):
    name = models.CharField(max_length=255, unique=True)
    question_text = models.TextField()
    create_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    quizz = models.ManyToManyField(Quizz)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL,
                                 null=True)

    class Meta:
        verbose_name = "Question"

    def __str__(self):

        return self.name


class Answer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    answer_text = models.TextField()
    question = models.ManyToManyField(Question, through="QuestionsAnswers")

    class Meta:
        verbose_name = "Answer"

    def __str__(self):

        return self.name


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    quizz = models.ForeignKey(Quizz, on_delete=models.SET_NULL, null=True)
    score = models.PositiveSmallIntegerField(null=True)
    last_date = models.DateTimeField()
    success = models.BooleanField()

    class Meta:
        verbose_name = "Result"

    def __str__(self):

        return f"Score de {self.user.username} sur le quizz {self.quizz.name}"


class QuestionsAnswers(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.SET_NULL,
                                 null=True)
    answer = models.ForeignKey(Answer, on_delete=models.SET_NULL, null=True)
    right_answer = models.BooleanField()

    class Meta:
        verbose_name = "QuestionsAnswers"

    def __str__(self):

        return f"{self.question} {self.answer}"

quizz/forms.py
from django import forms
import re


class AccountForm(forms.Form):
    first_name = forms.CharField(max_length=30, label="Prénom")
    last_name = forms.CharField(max_length=30, label="Nom")
    username = forms.CharField(max_length=150, label="Nom d'utilisateur")
    mail = forms.EmailField(label="E-mail")
    password = forms.CharField(
        label="Mot de passe",
        help_text="Longueur minimale de 12 caractères.",
        widget=forms.PasswordInput,
    )

    def clean_password(self):
        password = self.cleaned_data["password"]
        test = r"\S{12,}"
        if not re.match(test, password):
            raise forms.ValidationError(
                "Il faut une longueur minimale de 12 caractères!"
            )

        return password

quizz/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db import IntegrityError
from django.db import transaction
import json
import datetime

from .forms import AccountForm
from .models import User, Quizz, Question, QuestionsAnswers, Result
from .utils import answer_right_or_wrong, calulate_final_result, calulate_final_right_answer


def page_not_found_view(request, exception):
    return render(request, "core/404.html")


def page_server_not_found(request):
    return render(request, "core/500.html")


def account_create(request):
    if not request.user.is_authenticated:
        form = AccountForm(request.POST or None)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            username = form.cleaned_data["username"]
            mail = form.cleaned_data["mail"]
            password = form.cleaned_data["password"]
            try:
                with transaction.atomic():
                    user = User.objects.create_user(username, mail, password)
                    user.first_name, user.last_name = first_name, last_name
                    user.save()
                    login(request, user)
                    return redirect("account")
            except IntegrityError:
                messages.add_message(
                    request,
                    messages.WARNING,
                    "Un compte existe déjà avec ce nom d'utilisateur.\
                                      Merci d'en choisir un autre.",
                )
    else:
        return redirect("account")

    return render(request, "account/account_create.html", locals())


@login_required(login_url="/connexion")
def account(request):

    if request.method == "POST":
        user_id = request.user.id
        user = User.objects.get(pk=user_id)
        user.delete()
        logout(request)
        return redirect("/connexion")

    return render(request, "account/account.html", locals())


def quizz(request):
    category = request.GET.get("category")
    if category:
        quizz_list = Quizz.objects.filter(category=category)
    else:
        quizz_list = Quizz.objects.all()
    if not quizz_list:
        messages.add_message(request, messages.WARNING, "Pas de quizz.")

    return render(request, "quizz/quizz.html", locals())


def unique_quizz(request, id_quizz):
    quizz = Quizz.objects.get(pk=id_quizz)
    questions = Question.objects.filter(quizz__pk=id_quizz).order_by("id")
    right_answers = QuestionsAnswers.objects.filter(
        question__in=questions, right_answer=True
    )
    if request.is_ajax and request.method == "POST":
        answer_user_id = eval(request.POST.getlist("answer_id")[0])
        total_result = answer_right_or_wrong(answer_user_id)
        final_result = calulate_final_result(total_result, questions)
        final_right_answer = calulate_final_right_answer(right_answers)     
        Result.objects.update_or_create(
            user=request.user,
            quizz=quizz,
            defaults={
                "score": total_result,
                "last_date": datetime.datetime.now(),
                "success": final_result,
            },
        )
        response_data = {}
        response_data["right_answers"] = final_right_answer
        response_data["total_result"] = total_result
        response_data["final_result"] = final_result
        return HttpResponse(json.dumps(response_data),
                            content_type="application/json")

    return render(request, "quizz/unique_quizz.html", locals())


def results(request):
    if request.user.is_authenticated:
        results = Result.objects.filter(user=request.user)\
                 .order_by("-last_date")

    return render(request, "quizz/results.html", locals())

quizz/templates/quizz/quizz.html
{% extends "base.html" %}
{% block content %}
    <div class="col-lg-12">
        <h1>Quizz</h1>
        {% if user.is_authenticated %}
            <p id="pres">Cliquez sur le quizz que vous souhaitez tester.</p>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="row col-lg-12">
                {% for quizz in quizz_list%}
                    <div class="col-lg-12">
                        <p><strong><a href="{% url 'quizz_page' id_quizz=quizz.id %}">{{ quizz.name }} - {{ quizz.question_set.count }} questions</a></strong></p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h3><a href="/connexion">Connectez-vous</a> pour accéder aux quizzs !</h3>
        {% endif %}
    </div>
{% endblock %}

quizz/templates/quizz/results.html
{% extends "base.html" %}
{% block content %}

    <div>
        <h1 id="test">Mes résultats</h1>
    </div>
    {% if user.is_authenticated %}
        {% if results %}
            <div class="col-lg-12">
                <p>Voici tous les quizz que vous avez remplis. Vous pouvez les refaire si vous souhaitez améliorer votre score.</p>
            </div>
            {% for result in results %}
                <div class="col-lg-12">
                    <p><strong><a href="{% url 'quizz_page' id_quizz=result.quizz.id %}">{{ result.quizz.name }}</a></strong> tenté la dernière fois le {{ result.last_date|date:"j F Y" }}, résultat : {{ result.score }} bonnes réponses sur {{ result.quizz.question_set.count }} questions.</p>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-lg-12">
                <p><strong>Vous n'avez pas encore tenté de quizz. Retrouvez-les tous <a href="{% url 'quizz' %}">ici</a>.</strong></p>
            </div>
        {% endif %}
    {% else %}
        <h3><a href="/connexion">Connectez-vous</a> pour accéder à vos résultats.</h3>
    {% endif %}

{% endblock %}

quizz/templates/quizz/unique_quizz.html
{% extends "base.html" %}
{% block content %}

    <div id="h2">
        <h2 id="test">{{quizz.name}}</h2>
    </div>
    {% if user.is_authenticated %}
        <form method="post" id="quizz-form">
            {% csrf_token %}
            {% for question in questions %}
            <div class="question" id="{{ question.id }}">
                <p><strong>{{ forloop.counter }}) {{ question.question_text }}</strong></p>
                    {% for answer in question.answer_set.all %}
                        <p id="{{ question.id }}{{ answer.id }}">
                            <input id="answer_id" type="checkbox" name="{{ question.id }}" value="{{ answer.id }}"> {{ forloop.counter }}) {{ answer.answer_text }}
                        </p>
                    {% endfor %}
            </div>    
            {% endfor %}
            <div class="col-lg-12 col-sm-12">
                <input class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" type="submit" value="Sauvegarder" id="submit" />
            </div>
        </form>
    {% else %}
        <h3><a href="/connexion">Connectez-vous</a> pour accéder au quizz !</h3>
    {% endif %}
    <script src="https://code.jquery.com/jquery-1.12.3.js" integrity="sha256-1XMpEtA4eKXNNpXcJ1pmMPs8JV+nwLdEqwiJeCQEkyc=" crossorigin="anonymous"></script>
    <script src="../static/js/javascript.js"></script>
    <script>
        window.onload = cleanPage();
        $("#submit").click(function (e) {
            e.preventDefault();
            let checkedBoxes = document.querySelectorAll('input[id=answer_id]:checked');
            let questions = document.querySelectorAll('[class=question]');
            let toSend = checkIfSend(questions, checkedBoxes);
            let url = "{% url 'quizz_page' id_quizz %}";
            if (toSend===true) {
                main(checkedBoxes, url)
            }
        })
    </script>
{% endblock %}